// Generates dist/fizzbuzz-nothing.js: the FIZZBUZZ program as one expression
// with every name mechanically substituted away, proving the `const`
// definitions in fizzbuzz.js are only abbreviations.
//
// Usage: node inline.js

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, 'fizzbuzz.js'), 'utf8');

// Collect every `export const NAME = <expr>;` — expressions contain no
// semicolons, so each definition ends at the first one.
const definitions = new Map();
for (const [, name, expr] of source.matchAll(
  /export const (\w+) =([^;]*);/g
)) {
  definitions.set(name, expr.replace(/\s+/g, ' ').trim());
}

if (!definitions.has('FIZZBUZZ')) {
  throw new Error('FIZZBUZZ definition not found in fizzbuzz.js');
}

// Repeatedly substitute names for their (parenthesized) definitions until
// none remain. Names are ALL_CAPS and parameters are lowercase, so a
// word-boundary match cannot capture a bound variable.
const namePattern = new RegExp(
  `\\b(${[...definitions.keys()].join('|')})\\b`,
  'g'
);

let expression = definitions.get('FIZZBUZZ');
let previous;
do {
  previous = expression;
  expression = expression.replace(
    namePattern,
    (_, name) => `(${definitions.get(name)})`
  );
} while (expression !== previous);

const output = `// FizzBuzz with nothing: ${expression.length} characters of
// single-argument arrow functions. Generated by inline.js — do not edit.
export default
${expression};
`;

mkdirSync(join(here, 'dist'), { recursive: true });
writeFileSync(join(here, 'dist', 'fizzbuzz-nothing.js'), output);
console.log(
  `dist/fizzbuzz-nothing.js written (${expression.length} characters)`
);
